CASE_DETAIL_HTML = r"""
<!doctype html>
<html lang="ru">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Карточка дела — Digital Legal Concierge</title>
<style>
:root{--bg:#f4f6fa;--surface:#fff;--ink:#172033;--muted:#667085;--line:#e4e7ec;--primary:#3157d5;--primary-soft:#eef2ff;--green:#14804a;--green-soft:#ecfdf3;--red:#b42318;--red-soft:#fef3f2;--amber:#a15c00;--amber-soft:#fff7e6;--shadow:0 12px 34px rgba(16,24,40,.07)}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Arial,sans-serif}header{background:linear-gradient(135deg,#111827,#26334f);color:#fff;padding:20px 24px}header .inner{max-width:1180px;margin:auto;display:flex;justify-content:space-between;gap:18px;align-items:center}h1{font-size:23px;margin:0 0 4px}header p{margin:0;color:#d0d5dd;font-size:13px}.links,.row,.actions{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.button,button{border:0;border-radius:10px;padding:9px 12px;background:var(--primary);color:#fff;font-weight:750;cursor:pointer;text-decoration:none;display:inline-block}.secondary{background:#475467}main{max-width:1180px;margin:auto;padding:22px}.hero{display:flex;justify-content:space-between;gap:18px;align-items:flex-start;margin-bottom:14px}.hero h2{margin:0 0 5px}.muted{color:var(--muted);font-size:13px}.badge{display:inline-flex;border-radius:999px;padding:6px 10px;background:var(--primary-soft);color:#2445b5;font-size:12px;font-weight:750}.metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:11px}.metric,.card{background:#fff;border:1px solid var(--line);border-radius:15px;padding:15px;box-shadow:var(--shadow)}.metric b{display:block;font-size:17px;margin-bottom:4px}.metric span{color:var(--muted);font-size:12px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:13px;margin-top:14px}.card h3{margin:0 0 10px;font-size:17px}.action-box{background:var(--primary-soft);border:1px solid #c7d2fe;border-radius:12px;padding:12px;margin:12px 0}.data-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.cell{background:#f8fafc;border-radius:10px;padding:9px}.cell span{display:block;color:var(--muted);font-size:11px;margin-bottom:3px}.item{border-top:1px solid var(--line);padding:10px 0}.item:first-of-type{border-top:0}.status{min-height:22px;margin:10px 0}.bad{color:var(--red)}.warn{color:var(--amber)}.ok{color:var(--green)}.loading,.error,.empty{padding:34px;text-align:center;border:1px dashed var(--line);border-radius:16px;color:var(--muted);background:#fff}.error{color:var(--red);background:var(--red-soft)}@media(max-width:850px){.metrics,.grid{grid-template-columns:1fr 1fr}}@media(max-width:620px){header .inner,.hero{align-items:flex-start;flex-direction:column}.metrics,.grid,.data-grid{grid-template-columns:1fr}main{padding:14px}}
</style>
</head>
<body>
<header><div class="inner"><div><h1>⚖ Карточка дела</h1><p>Контекст недоставленного Telegram-уведомления</p></div><div class="links"><a class="button secondary" href="/admin/notification-delivery/ui">Telegram-доставка</a><a class="button secondary" href="/admin-ui">Админка</a><a class="button secondary" href="/operator">Все разделы</a></div></div></header>
<main><div id="status" class="status" role="status" aria-live="polite"></div><div id="content"><div class="loading">Загрузка карточки дела…</div></div></main>
<script>
const caseId=Number('__CASE_ID__');let token='';const content=document.getElementById('content'),statusBox=document.getElementById('status');
function esc(v){return String(v??'').replace(/[&<>\x22\x27]/g,c=>c==='&'?'&amp;':c==='<'?'&lt;':c==='>'?'&gt;':c.charCodeAt(0)===34?'&quot;':'&#39;')}
function feedback(text,state=''){statusBox.textContent=text;statusBox.className='status '+state}
function dt(v){return v?new Intl.DateTimeFormat('ru-RU',{dateStyle:'short',timeStyle:'short'}).format(new Date(v)):'—'}
async function api(path){const r=await fetch(path,{credentials:'same-origin',cache:'no-store',headers:{'x-admin-token':token}});if(r.status===401||r.status===403){location.href='/login';throw new Error('Сессия истекла или недостаточно прав')}const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||'Ошибка запроса');return d}
function docItem(x){return `<div class="item"><b>${esc(x.title)} · версия ${esc(x.version)}</b><br><span class="badge">${esc(x.status_label||'Статус уточняется')}</span><div class="muted">${esc(x.file_name||'Файл')} · ${esc(x.type||'')}</div>${x.lawyer_comment?`<div class="action-box"><b>Комментарий юриста</b>${esc(x.lawyer_comment)}</div>`:''}</div>`}
function paymentItem(x){return `<div class="item"><b>${esc(x.title)}</b><div>${esc(x.amount)} ₽ · ${esc(x.status)}</div></div>`}
function render(d){const x=d.case||{},client=d.client||null,docs=d.documents||[],payments=d.payments||[];const current=docs.filter(v=>v.status!=='ARCHIVED'),archived=docs.filter(v=>v.status==='ARCHIVED');content.innerHTML=`<div class="hero"><div><h2>${esc(x.number||'Дело')}</h2><div class="muted">${esc(x.route_label||'Юридическое обращение')} · обновлено ${esc(dt(x.updated_at))}</div></div><span class="badge">${esc(x.status_label||'Статус уточняется')}</span></div><div class="metrics"><article class="metric"><b>${esc(x.sla_label||'SLA не определён')}</b><span>срок: ${esc(dt(x.sla_due_at))}</span></article><article class="metric"><b>${esc(x.lawyer_name||'Не назначен')}</b><span>ответственный юрист</span></article><article class="metric"><b>${current.length}</b><span>актуальных документов</span></article><article class="metric"><b>${payments.length}</b><span>платёжных записей</span></article></div><div class="action-box"><b>Рекомендуемое действие</b>${esc(x.next_action||'Проверить актуальное состояние дела')}</div><div class="grid"><section class="card"><h3>Клиент и дело</h3><div class="data-grid"><div class="cell"><span>Клиент</span>${esc(client?.name||'Не найден')}</div><div class="cell"><span>Telegram</span>${esc(client?.username?('@'+client.username):'username не указан')}</div><div class="cell"><span>Маршрут</span>${esc(x.route_label||'—')}</div><div class="cell"><span>Ответственный</span>${esc(x.lawyer_name||'Не назначен')}</div></div><div class="actions" style="margin-top:12px"><a class="button" href="/message-center/ui">Открыть переписку</a><a class="button secondary" href="/lawyer/workspace/ui">Кабинет юриста</a></div></section><section class="card"><h3>Документы</h3>${current.length?current.map(docItem).join(''):'<div class="empty">Актуальных документов нет.</div>'}${archived.length?`<details><summary>История версий (${archived.length})</summary>${archived.map(docItem).join('')}</details>`:''}<div class="actions" style="margin-top:12px"><a class="button" href="/document-access/review/ui">Центр проверки</a></div></section><section class="card"><h3>Платежи</h3>${payments.length?payments.map(paymentItem).join(''):'<div class="empty">Платёжных записей нет.</div>'}</section><section class="card"><h3>Операционные действия</h3><p class="muted">Используйте профильные центры: они повторно проверяют права, snapshot и допустимость перехода.</p><div class="actions"><a class="button" href="/admin/notification-delivery/ui">Вернуться к доставке</a><a class="button secondary" href="/admin-ui">Все дела</a><a class="button secondary" href="/admin/sla/ui">SLA</a></div></section></div>`;feedback('Карточка загружена','ok')}
function showError(e){content.innerHTML=`<div class="error"><b>Не удалось открыть дело #${esc(caseId)}</b><p>${esc(e.message||e)}</p><button onclick="load()">Повторить</button> <a class="button secondary" href="/admin/notification-delivery/ui">К доставке</a></div>`;feedback(e.message||String(e),'bad')}
async function load(){content.innerHTML='<div class="loading">Загрузка карточки дела…</div>';feedback('');try{render(await api('/admin/case-workspace/'+caseId))}catch(e){showError(e)}}
async function boot(){try{const r=await fetch('/auth/session',{credentials:'same-origin',cache:'no-store'});if(!r.ok){location.href='/login';return}const s=await r.json();if(!(s.roles||[s.role]).includes('admin'))throw new Error('Требуется роль администратора');token=s.api_token||'';await load()}catch(e){showError(e)}}
boot();
</script>
</body>
</html>
"""
