from enum import StrEnum
class PaymentCode(StrEnum):
    M1_INITIAL_PAYMENT='M1_INITIAL_PAYMENT'; M1_COURT_PAYMENT='M1_COURT_PAYMENT'; M1_SUCCESS_FEE='M1_SUCCESS_FEE'; M2_CONSULTATION_PAYMENT='M2_CONSULTATION_PAYMENT'
