TEMPLATES = {
    "case_created": "🆕 Новое обращение {case_number}.",
    "lawyer_assigned": "👨‍⚖ По делу {case_number} назначен юрист: {lawyer_name}.",
    "document_uploaded": "📄 Загружен новый документ по делу {case_number}.",
    "document_status_changed": "📄 Статус документа «{document_title}» изменен: {status}.",
    "documents_required": "📎 По делу {case_number} необходимо загрузить документы: {documents}. Срок: {deadline}.",
    "documents_required_repeat": "⏰ Напоминание по делу {case_number}: документы еще не загружены. Осталось: {documents}.",
    "document_review_overdue": "⚠️ Просрочена проверка документов по делу {case_number}. Ответственный: {lawyer_name}.",
    "payment_created": "💳 Выставлен платеж по делу {case_number}: {amount} ₽. Оплатить до {deadline}.",
    "payment_paid": "✅ Оплата подтверждена по делу {case_number}.",
    "payment_reminder": "⏰ Напоминание: по делу {case_number} ожидается оплата {amount} ₽ до {deadline}.",
    "payment_overdue": "⚠️ По делу {case_number} просрочена оплата {amount} ₽. Выполните оплату, чтобы не задерживать следующий этап.",
    "consultation_booked": "📅 Консультация подтверждена: {date}. Формат: {format}.",
    "consultation_24h": "⏰ Напоминание: консультация по делу {case_number} состоится завтра, {date}.",
    "consultation_2h": "⏰ До консультации по делу {case_number} осталось 2 часа. Начало: {date}.",
    "consultation_30m": "⏰ До консультации по делу {case_number} осталось 30 минут. Подготовьте вопросы и документы.",
    "consultation_starting": "📞 Консультация по делу {case_number} начинается сейчас.",
    "client_action_required": "📌 По делу {case_number} требуется ваше действие: {action}. Срок: {deadline}.",
    "client_action_repeat": "⏰ Напоминание по делу {case_number}: действие «{action}» еще не выполнено.",
    "task_due_soon": "⏳ Задача «{task_title}» по делу {case_number} должна быть выполнена до {deadline}.",
    "task_overdue": "⚠️ Просрочена задача «{task_title}» по делу {case_number}. Просрочка: {overdue}.",
    "task_escalated": "🚨 Эскалация: задача «{task_title}» по делу {case_number} просрочена. Ответственный: {lawyer_name}.",
    "case_without_lawyer": "🚨 Дело {case_number} остается без назначенного юриста более {elapsed}.",
    "claim_30_days_expired": "📨 По делу {case_number} истекли 30 дней после претензии. Проверьте следующий шаг.",
    "court_stage_started": "🏛 Дело {case_number} перешло в судебный этап.",
    "court_event_reminder": "🏛 Напоминание: {event_title} по делу {case_number} состоится {date}.",
}
