NOTIFICATION_RULES = {
    "CASE_CREATED": {"recipients": ["admin"], "template": "case_created"},
    "LAWYER_ASSIGNED": {"recipients": ["client", "lawyer"], "template": "lawyer_assigned"},
    "DOCUMENT_UPLOADED": {"recipients": ["admin", "lawyer"], "template": "document_uploaded"},
    "DOCUMENT_STATUS_CHANGED": {"recipients": ["client"], "template": "document_status_changed"},
    "DOCUMENTS_REQUIRED": {"recipients": ["client"], "template": "documents_required"},
    "DOCUMENTS_REQUIRED_REPEAT": {"recipients": ["client"], "template": "documents_required_repeat"},
    "DOCUMENT_REVIEW_OVERDUE": {"recipients": ["lawyer", "admin"], "template": "document_review_overdue"},
    "PAYMENT_CREATED": {"recipients": ["client"], "template": "payment_created"},
    "PAYMENT_PAID": {"recipients": ["client", "admin"], "template": "payment_paid"},
    "PAYMENT_REMINDER": {"recipients": ["client"], "template": "payment_reminder"},
    "PAYMENT_OVERDUE": {"recipients": ["client", "admin"], "template": "payment_overdue"},
    "M2_CONSULTATION_BOOKED": {"recipients": ["client", "lawyer", "admin"], "template": "consultation_booked"},
    "CONSULTATION_REMINDER_24H": {"recipients": ["client", "lawyer"], "template": "consultation_24h"},
    "CONSULTATION_REMINDER_2H": {"recipients": ["client", "lawyer"], "template": "consultation_2h"},
    "CONSULTATION_REMINDER_30M": {"recipients": ["client", "lawyer"], "template": "consultation_30m"},
    "CONSULTATION_STARTING": {"recipients": ["client", "lawyer"], "template": "consultation_starting"},
    "CLIENT_ACTION_REQUIRED": {"recipients": ["client"], "template": "client_action_required"},
    "CLIENT_ACTION_REPEAT": {"recipients": ["client"], "template": "client_action_repeat"},
    "TASK_DUE_SOON": {"recipients": ["lawyer"], "template": "task_due_soon"},
    "TASK_OVERDUE": {"recipients": ["lawyer"], "template": "task_overdue"},
    "TASK_ESCALATED": {"recipients": ["admin"], "template": "task_escalated"},
    "CASE_WITHOUT_LAWYER": {"recipients": ["admin"], "template": "case_without_lawyer"},
    "CLAIM_30_DAYS_EXPIRED": {"recipients": ["lawyer", "admin"], "template": "claim_30_days_expired"},
    "COURT_STAGE_STARTED": {"recipients": ["client", "lawyer"], "template": "court_stage_started"},
    "COURT_EVENT_REMINDER": {"recipients": ["client", "lawyer"], "template": "court_event_reminder"},
}
