from enum import StrEnum
class RouteCode(StrEnum):
    M1='M1'; M2='M2'
class CaseStatus(StrEnum):
    NEW='NEW'; CALCULATOR_STARTED='CALCULATOR_STARTED'; CALCULATED='CALCULATED'; CLIENT_DECISION='CLIENT_DECISION'
    M1_DOCUMENTS_PENDING='M1_DOCUMENTS_PENDING'; M1_DOCUMENTS_RECEIVED='M1_DOCUMENTS_RECEIVED'; M1_LAWYER_REVIEW='M1_LAWYER_REVIEW'; M1_DOCS_REQUESTED='M1_DOCS_REQUESTED'; M1_ACCEPTED='M1_ACCEPTED'; M1_REJECTED='M1_REJECTED'; M1_CONTRACT_READY='M1_CONTRACT_READY'; M1_WAITING_PAYMENT_30000='M1_WAITING_PAYMENT_30000'; M1_PAYMENT_30000_RECEIVED='M1_PAYMENT_30000_RECEIVED'; M1_POWER_OF_ATTORNEY='M1_POWER_OF_ATTORNEY'; M1_POA_RECEIVED='M1_POA_RECEIVED'; M1_CLAIM_PREPARATION='M1_CLAIM_PREPARATION'; M1_CLAIM_SENT='M1_CLAIM_SENT'; M1_WAITING_30_DAYS='M1_WAITING_30_DAYS'; M1_COURT_STAGE='M1_COURT_STAGE'; M1_WAITING_PAYMENT_70000='M1_WAITING_PAYMENT_70000'; M1_PAYMENT_70000_RECEIVED='M1_PAYMENT_70000_RECEIVED'; M1_ENFORCEMENT='M1_ENFORCEMENT'; M1_MONEY_RECEIVED='M1_MONEY_RECEIVED'; M1_WAITING_SUCCESS_FEE='M1_WAITING_SUCCESS_FEE'; M1_SUCCESS_FEE_RECEIVED='M1_SUCCESS_FEE_RECEIVED'; M1_CLOSED='M1_CLOSED'
    M2_CONSULTATION_ROUTE='M2_CONSULTATION_ROUTE'; M2_DESCRIPTION_PENDING='M2_DESCRIPTION_PENDING'; M2_DOCUMENTS_OPTIONAL='M2_DOCUMENTS_OPTIONAL'; M2_SLOT_PENDING='M2_SLOT_PENDING'; M2_PAYMENT_PENDING='M2_PAYMENT_PENDING'; M2_CONSULTATION_BOOKED='M2_CONSULTATION_BOOKED'; M2_CONSULTATION_DONE='M2_CONSULTATION_DONE'; M2_TO_M1='M2_TO_M1'; M2_CLOSED='M2_CLOSED'
    ERROR='ERROR'; ARCHIVED='ARCHIVED'
