from enum import StrEnum


class ConsultationStatus(StrEnum):
    DESCRIPTION_PENDING = "DESCRIPTION_PENDING"
    DOCUMENTS_OPTIONAL = "DOCUMENTS_OPTIONAL"
    SLOT_PENDING = "SLOT_PENDING"
    SLOT_RESERVED = "SLOT_RESERVED"
    PAYMENT_PENDING = "PAYMENT_PENDING"
    PAID_PENDING_CONFIRMATION = "PAID_PENDING_CONFIRMATION"
    CONFIRMED = "CONFIRMED"
    DECLINED = "DECLINED"
    BOOKED = "BOOKED"
    DONE = "DONE"
    CANCELLED = "CANCELLED"
    RESCHEDULED = "RESCHEDULED"
    CLOSED = "CLOSED"
