from enum import StrEnum
class DocumentStatus(StrEnum):
    REQUIRED='REQUIRED'; UPLOADED='UPLOADED'; ON_REVIEW='ON_REVIEW'; APPROVED='APPROVED'; REJECTED='REJECTED'; NEEDS_REUPLOAD='NEEDS_REUPLOAD'; ARCHIVED='ARCHIVED'
