from enum import StrEnum


class PaymentStatus(StrEnum):
    PENDING = "PENDING"
    WAITING_CONFIRMATION = "WAITING_CONFIRMATION"
    PAID = "PAID"
    PAID_REVIEW = "PAID_REVIEW"
    REFUND_PENDING = "REFUND_PENDING"
    REFUND_DECLINED = "REFUND_DECLINED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    REFUNDED = "REFUNDED"
    EXPIRED = "EXPIRED"
