from enum import StrEnum


class PaymentStatus(StrEnum):
    PENDING = "PENDING"
    WAITING_CONFIRMATION = "WAITING_CONFIRMATION"
    PAID = "PAID"
    PAID_REVIEW = "PAID_REVIEW"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    REFUNDED = "REFUNDED"
    EXPIRED = "EXPIRED"
