from __future__ import annotations

import secrets
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ENV = ROOT / '.env'
EXAMPLE = ROOT / '.env.example'


def read_env() -> dict[str, str]:
    source = ENV if ENV.exists() else EXAMPLE
    data: dict[str, str] = {}
    for line in source.read_text(encoding='utf-8').splitlines():
        if not line or line.strip().startswith('#') or '=' not in line:
            continue
        k, v = line.split('=', 1)
        data[k.strip()] = v.strip()
    return data


def write_env(data: dict[str, str]) -> None:
    ordered = [
        'APP_ENV','DATABASE_URL','BOT_TOKEN','RUN_BOT','RUN_SCHEDULER','ADMIN_API_TOKEN',
        'LEGAL_KEY_RATE','STORAGE_DIR','PAYMENT_WEBHOOK_SECRET','PUBLIC_BASE_URL',
        'PAYMENT_PROVIDER','YOOKASSA_SHOP_ID','YOOKASSA_SECRET_KEY'
    ]
    lines = ['# Generated by scripts/production_wizard.py']
    for key in ordered:
        if key in data:
            lines.append(f'{key}={data[key]}')
    for key in sorted(set(data) - set(ordered)):
        lines.append(f'{key}={data[key]}')
    ENV.write_text('\n'.join(lines) + '\n', encoding='utf-8')


def ask(prompt: str, current: str = '', secret: bool = False) -> str:
    suffix = f' [{current}]' if current and not secret else ''
    value = input(f'{prompt}{suffix}: ').strip()
    return value or current


def main() -> None:
    data = read_env()
    print('=== Настройка Telegram-бота для запуска ===')
    data['APP_ENV'] = ask('APP_ENV local/production', data.get('APP_ENV', 'local')) or 'local'
    data['BOT_TOKEN'] = ask('BOT_TOKEN от BotFather', data.get('BOT_TOKEN', 'CHANGE_ME'))
    data['RUN_BOT'] = ask('Запускать Telegram-бот? true/false', data.get('RUN_BOT', 'true') or 'true')
    data['RUN_SCHEDULER'] = ask('Запускать scheduler? true/false', data.get('RUN_SCHEDULER', 'true') or 'true')
    data['PUBLIC_BASE_URL'] = ask('Публичный URL backend', data.get('PUBLIC_BASE_URL', 'http://localhost:8000'))
    if data.get('ADMIN_API_TOKEN', 'dev-admin-token') in {'dev-admin-token', 'CHANGE_ME_LONG_RANDOM_TOKEN', ''}:
        data['ADMIN_API_TOKEN'] = secrets.token_urlsafe(32)
        print('ADMIN_API_TOKEN сгенерирован автоматически.')
    if data.get('PAYMENT_WEBHOOK_SECRET', 'change-this-payment-secret') in {'change-this-payment-secret', 'CHANGE_ME_LONG_RANDOM_SECRET', ''}:
        data['PAYMENT_WEBHOOK_SECRET'] = secrets.token_urlsafe(32)
        print('PAYMENT_WEBHOOK_SECRET сгенерирован автоматически.')
    provider = ask('Платежи fake/yookassa', data.get('PAYMENT_PROVIDER', 'fake')) or 'fake'
    data['PAYMENT_PROVIDER'] = provider
    if provider == 'yookassa':
        data['YOOKASSA_SHOP_ID'] = ask('YOOKASSA_SHOP_ID', data.get('YOOKASSA_SHOP_ID', ''))
        data['YOOKASSA_SECRET_KEY'] = ask('YOOKASSA_SECRET_KEY', data.get('YOOKASSA_SECRET_KEY', ''), secret=True)
    write_env(data)
    print('\n.env сохранен.')
    print('Дальше: python scripts/init_db.py && python scripts/launch_check.py && python -m app.main')


if __name__ == '__main__':
    main()
